server:
  port: 8086

spring:
  application:
    name: chat-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chat_db}
    username: ${SPRING_DATASOURCE_USERNAME:archai}
    password: ${SPRING_DATASOURCE_PASSWORD:archai123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

services:
  ai:
    base-url: ${AI_SERVICE_URL:http://localhost:8084}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
